- dist/omi.js
- dist/omi.lite.js
- example/jsx-like-event/bundler.js
- example/jsx-like-event/hello.js
- src/event.js
- test/js/event.js
- 在表达式里可以正常使用分号：
```js
render() {
return  `
<div>
{{{img}}}
<h1 onclick={function(e){
console.log(this)
console.log(e)
console.log('test \\' test "double quote"')
console.log("test \\"")
}}>Hello, {{name}}!</h1>
</div>
`;
}
```
- 增加关于 jsx-like event binding 的单元测试
- 多行可以不用分号（见上面的例子）
> Better jsx-like event binding

- README.md
Hi @dntzhang!
I created a simple yet useful Chrome DevTools extension for Omi, and added to the README! Please inspect: https://github.com/f/omi-devtools
It simply uses the Element panel's sidebar since Omi uses shadow dom and doesn't need another elements view such as React or Vue have. This makes it powerful while debugging.
> add omi.js devtools links to readme

- packages/omi-cli/template/app/src/elements/app/logo.svg
Old one was a simple circle which looks static even it's rotating. New logo looks better while rotating.
> Replace template rotating logo with new

- packages/omi-cli/lib/init.js
Hi, I've found some bugs at omi-cli.
When I create omi project with omi-cli, project name doesn't change at package.json like this.
This is my screen shot after I run `omi init text` 
I think it is bug, so I fix it package.json name is same as project name like this.
Sorry for my poor English. If you can't understand, leave a comment. Thx!
> Save project name on package.json

- packages/omi-cli/lib/init-pr.js
- packages/omi-cli/lib/init-ts.js
There are **two more places**  have wrong path of node_modules path
- as-is: **mode**_modules
- to-be: **node**_modules
> fix wrong node package module path

- packages/omi-cli/lib/init-pr.js
- packages/omi-cli/lib/init-ts.js
- packages/omi-cli/lib/init.js
- packages/omi-cli/lib/utils.js
`omi-cli` current empty a directory, if directory is not empty after confirm.
It is little dangerous so in this commit, it is changed as only notice to user there has invalid file/directory except some of verified file/directory: **.git** directory.
**What changed is**
AS-IS:
1. Verify target directory is empty, or not
2. Confirm to user to empty
3. Empty target directory
4. Create a project
TO-BE:
1. Verify target directory is empty, or not
2. Verify there only valid directory/file, or not (i.e. **.git**)
3. Remove 'npm-debug.log',  'yarn-error.log', 'yarn-debug.log'
4. Create a project
**In addition**
Normally, we clone git on our local, then create a project, but current version cannot create a project if there is **.git**  so there are two advantages: 1. safety, 2. …
> omi-cli not to empty a directory, only verify valid a directory instead

- README.md
- remove `|` in README.md
- in table of markdown, we normally put double `|`, but there were triple `|`
> fix README.md - `|`

- packages/omi-cli/bin/omi
- packages/omi-cli/lib/init-template.js
- packages/omi-cli/package.json
There have many templates more and more so omi-cli size is being little heavy.
Thus, we decided to separate between **omi-cli** and **templates** from now, and new template will be stored on https://github.com/omijs with `template-` prefix. i.e **[template-ts](https://github.com/omijs/template-ts)**
How it creates a template, it does `git clone https://www.github.com/omijs/ts-{templateName}`.
**What added**
- add a new spec **omi-cli init-{templateName}**
``` bash
> omi-cli init-{templateName} {projectName}
> omi-cli init-cli-test myProject
```
- changed /packages/omi-cli/bin/omi
- added /packages/omi-cli/lib/init-template.js
- changed a version of omi-cli as **3.1.4**
[**NOTE**]If it is fine, we need to publish it @dntzhang 
**How to TEST**
I have already tested by my …
> omi-cli - init-template

- packages/omi-cli/lib/init-template.js
- packages/omi-cli/package.json
`omi-cli` template is execute npm install even though no package.json. 
This PR is disable ```npm install``` if no package.json
- fix not install npm if no package.json
- version up `omi-cli` as **3.2.2** from 3.2.1
**How to Test**
```bash
> npm i -g omi-cli-test@3.1.4
> omi-cli-test init-cli-test myPro
> cd myPro
```
verify there is **node_modules** or not
@dntzhang Please ```npm publish```, if you fine with it.
> omi-cli: not install npm if no package.json

- packages/omio/src/dom/index.js
- packages/omio/src/omi.js
- packages/omio/src/util.js
- packages/omio/src/vdom/component.js
- packages/omio/src/vdom/diff.js
- packages/omio/test/browser/util.js
`ref={e=>{}}` has a performance issue, and **preact** resolved the issue with new function **applyRef**.
**Changed**
Changed as using **applyRef** function same as **preact**
(REF: https://github.com/developit/preact/commit/f634d122dab064a34bad5dda83e36b50a8a7c488)
@dntzhang In this PR, I only added a test code for **applyRef**.
(https://github.com/Tencent/omi/compare/master...LeeHyungGeun:feature/createRef?expand=1#diff-927127f97d85209953b87a0a14e0cbc4R1)
> add applyRef/createRef in omio

- packages/omio/src/omi.js
`createRef` is now an object. preact already changed it as a function and it will return new everytime.
**Changed**
createdRef
- as-is: Object
- to-be: Function
> change createRef as a function from object

- packages/omi-cli/lib/init-ts.js
Since `gitignore` in `app-ts` template(`gitignore` is only exist in `app-ts-old`) changed as `.gitignore`, but it is still trying to rename so it occurs an error.
**Changed**
- check `gitignore` file exist, and rename if exist.
> Fix gitignore rename bug in app-ts(init ts)

- packages/omi-cli/template/app/src/elements/app/index.js
- packages/omi-cli/template/app/src/elements/omil/_index.css
- packages/omi-cli/template/app/src/elements/omil/index.omi
- packages/omi-cli/template/app/src/elements/omil/index.omi.js
Now omi-cli can provide SFC by omil when you create template in the first time, but error warning tips have not perfect when you use it without [omi-snippets](https://github.com/Wscats/omi-snippets), user experience is not so good for the time being, Although this is not a serious problem, I will follow up repairs.
> support SFC

- packages/omi-cli/template/app/src/elements/app-omil/index.omi
It's grammatical to have or not have 'class'. But I still recommend 'class'. So I add it back.
> Add class back

- packages/omix/utils/create.js
当组件使用了"lifetimes.ready"时，因为优先级较高，会出现覆盖的情况，使得注入失效
> omix - use "lifetimes.ready" instead of "ready" for priority reasons (since ver 2.2.3)

- packages/omi-mp/scripts/mp/parse.js
修复微信block载体在h5 下面出现宽度不是100%，增加绑定bindtap绑定bindclick事件
> 修复微信block载体在h5 下面出现宽度不是100%，增加绑定bindtap绑定bindclick事件

- packages/omix/utils/create.js
**bug**：多页面使用store，且在store更新时会对挂载在data上的$（'store数据'）会产生以下问题：
多次给$追加$，导致更新视图失败。
```javascript
// 两个页面更新store时产生如下
$.user
$.$.user
```
该提交是为了解决该问题，已通过测试
> fix(omix):solve recurring '$' in _update

- packages/omiv/examples/multiple-stores/src/App.vue
- packages/omiv/examples/multiple-stores/src/components/HelloWorld.vue
- packages/omiv/examples/multiple-stores/src/main.js
- packages/omiv/examples/simple/src/App.vue
- packages/omiv/examples/simple/src/components/HelloWorld.vue
- packages/omiv/examples/simple/src/main.js
- packages/omiv/src/vue.js
- packages/omiv/test/browser/components/child3.vue
- packages/omiv/test/browser/index.js
1. 更新了 child2 和 child3 test , $ 不需要再手动调用，但是 use 或者 useSelf 是需要的，主要还是通过这两个字段来收集依赖
2. examples 中的两个 demo， omiv 路径换成 src/omiv ， 便于本地调试
> fix(omiv): 修复 Ctor.options 没有被 $ 包裹 vm 依赖没有被 store 收集的问题

- packages/omix/README.md
- packages/omix/utils/create.js
1. README 的一处，应该是 typo...吧
2. 重命名了内部使用的 buffer 和 tick lock，避免命名冲突
3. 将对 buffer 的前置创建改成了使用时 check，减少漏掉创建的可能（之前普通组件就会漏掉，没仔细看 _omixComponents）
4. 由于引入了 tick 聚合，可以在 replace store.data 的时候直接报错（比整个 break 掉要好），并提示应该 assign prop（因为 observe store.data 本身这个事情其实是为 omix 服务的，就还是实现在 omix 里了，不改 obaa）
> rename internal var to avoid collision - omix

- packages/omi/examples/perfs/env.js
Please consider this pull request. It replaces the antiquated word "slave" with the modern "replica". The example still works perfectly fine, I've tested it.
> replace slave label with replica

- packages/obaa/README.md
- packages/obaa/index.js
Maybe we can trick obaa to trigger change callback as assigning temporary value (\_\_deleted\_\_) to the prop just before delete it.
> make obaa trigger after prop delete

- README.CN.md
- README.md
- packages/omi-cli/template/app-ts/src/hello-omi.tsx
fix:README JS code block syntax error on line 772
fix:README.CN JS code block syntax error on line 844
fix HelloElement example , There may be event binding error, data.abc props are not defined
fix:fix omi-cli ts template
> Fix HelloElement example and docs and omi-cli-ts

- packages/omi/src/omi.d.ts
- remove nonexistent function declarations: `tick`, `nextTick`, `observe`
- add type declaration for `createRef`
> fix(types): fix function declaration in omi.d.ts

- packages/omi/src/omi.d.ts
- Fixed type incompatibility when `ref` was used as an element attribute
> fix(types): fix type declaration for `Ref<T>`

- components/common/package.json
- components/common/src/color.js
- components/common/src/index.ts
- components/common/theme.scss
- [@ctrl/tinycolor](https://github.com/scttcper/tinycolor) is a color lib with type (with typescript), may be we can import it and remove `color-convert` `color-name` `color-string``common/src/color.js`
- use map simplify theme in `components/common/src/index.ts`
If you think this is possible, i can remove `color.js`.
> refactor(common): use @ctrl/tinycolor with type replace color

- packages/omi-cli/bin/omi
❌File conflicts are displayed when omi-cli has no incoming parameters instead of no incoming parameters
✅FIxed：
> fix：when omi-cli has no parameters

- components/table/src/demo.tsx
- components/table/src/index.tsx
根据 #744 ，OMIU Table 添加合并单元格功能。
使用：
+ 通过 props `cellSpanOption` 设置合并单元格，`cellSpanOption` 中通过方法 `bodyCellSpan({row, column})` 设置 `body` 单元格的合并。
+ 在 `bodyCellSpan({row, column})` 中通过 `row` 和 `column` 定位相应的单元格，返回 `colspan` 和 `rowspan` 属性指定合并的行数；同时需要指定不渲染的单元格，设置 `colspan` 和 `rowspan` 为 0 并返回即可。
存在问题和后续想法：
+ 排序后，合并 body 列可能出现位置错乱，这是因为合并单元格时指定单元格是通过单元格的位置而不是根据内容进行合并，还在思考更好的解决方法；
+ 还需要实现表格的头部和脚部的合并单元格功能、添加自定义合并单元格后渲染的内容。
> feat(table): add table body cell span 

- components/popover/src/demo.tsx
- components/popover/src/index.scss
- components/popover/src/index.tsx
在完成 #744 ，OMIU Table 添加 filter 功能中, 发现 popover 组件会受到外部 table 组件中的如下样式影响，
``` css
th, td {
overflow: hidden; //虽然去掉filter就可以正常展示，但是会影响 table cell 内容溢出，所以不建议改
}
```
最后期望是将 popover append 到 body 下，参考资料：
1. [spectrum-web-components 的 overlay](https://opensource.adobe.com/spectrum-web-components/components/overlay/) 这个的实现太麻烦了，用了一个 stack 维护。
2. [vue2 element-ui popover](https://element.eleme.io/#/zh-CN/component/popover)
最后参考了element-ui的方式，直接操作dom了，感觉还是不够优雅，希望有同学能出出点子。
存在问题：
1. popover 内的 slot 内容 更新时，会全部获取再赋值到 body 下的 popover 中，性能差
2. 边界条件可能考虑的不够，popover实现之后，再继续完成 table 的 filter
3. 这个PR可以晚点合，有了好点子我改下代码再合
> feat: support popover to body

- tdesign/desktop/src/link/index.html
- tdesign/desktop/src/link/link.md
- tdesign/desktop/src/link/link.tsx
- tdesign/desktop/src/link/style/index.ts
- tdesign/desktop/src/link/theme.tsx
- tdesign/desktop/src/link/type.ts
- tdesign/desktop/src/link/vite.config.js
> feat: add and init link component

- tdesign/desktop/src/button/tsconfig.json
- tdesign/desktop/tsconfig.omi.json
1. 今天遇到有人咨询，为什么跑组件的时候无法变异 jsx ，后来发现 因为root的tsconfig.json 使用了preserver  需要添加一个公共的 omi.json 进行管理jsx 编译
> 修复 site 使用的tsconfig 在 组件中无法使用的问题

- tdesign/desktop/site/src/components/web/common/index.tsx
- tdesign/desktop/site/src/components/web/divider/index.tsx
- tdesign/desktop/site/src/components/web/link/index.tsx
- tdesign/desktop/site/src/components/web/space/index.tsx
- tdesign/desktop/site/src/router.ts
- tdesign/desktop/src/divider/divider.tsx
- tdesign/desktop/src/divider/type.ts
- tdesign/desktop/src/space/_example/align.tsx
- tdesign/desktop/src/space/_example/break-line.tsx
- tdesign/desktop/src/space/_example/separator.tsx
- tdesign/desktop/src/space/_example/size.tsx
- tdesign/desktop/src/space/_example/vertical.tsx
- tdesign/desktop/src/space/index.html
- tdesign/desktop/src/space/space.tsx
- tdesign/desktop/src/space/type.ts
完善space的site，发现并解决之前的几个小bug
待解决问题
> feat: add space site and fix some bug

- tdesign/desktop/site/src/components/web/input/index.tsx
- tdesign/desktop/site/src/components/web/slider/index.tsx
- tdesign/desktop/site/src/router.ts
- tdesign/desktop/src/common.ts
- tdesign/desktop/src/input-number/index.tsx
- tdesign/desktop/src/input-number/sytle/index.ts
- tdesign/desktop/src/input-number/types.ts
- tdesign/desktop/src/input/index.tsx
- tdesign/desktop/src/input/sytle/index.ts
- tdesign/desktop/src/input/types.ts
- tdesign/desktop/src/slider/index.tsx
- tdesign/desktop/src/utils/observable.ts
1. input 和 input number 的实现
2. slider 对 input number 的依赖，更组件模式开发
> feat: input 和 input number 的实现

- tdesign/desktop/src/list/index.html
- tdesign/desktop/src/list/list-item-meta.tsx
- tdesign/desktop/src/list/list-item.tsx
- tdesign/desktop/src/list/list-us.md
- tdesign/desktop/src/list/list.md
- tdesign/desktop/src/list/list.tsx
- tdesign/desktop/src/list/style/index.ts
- tdesign/desktop/src/list/types.ts
- tdesign/desktop/src/list/vite.config.js
> add list beta 1.0.0

- tdesign/desktop/src/rate/_example/base.tsx
- tdesign/desktop/src/rate/_example/custom.tsx
- tdesign/desktop/src/rate/_example/status.tsx
- tdesign/desktop/src/rate/index.html
- tdesign/desktop/src/rate/index.tsx
- tdesign/desktop/src/rate/rate.tsx
- tdesign/desktop/src/rate/style/index.ts
- tdesign/desktop/src/rate/type.ts
- tdesign/desktop/src/rate/vite.config.js
初步完成rate组件
待完善内容：
问题：
1. 在实现rate组件的过程中，需要用到的color类型为string或Array<string>【tdesign统一给定】，对rate的颜色进行设置
```JSX
import { h, tag, WeElement } from 'omi'
import '../index'
@tag('rate-base')
export default class RateBase extends WeElement {
render() {
return <t-rate default-value={3} color={['#000', '#3281b0']}></t-rate>
}
}
```
如期望实现如下效果： 
目前只能在propTypes注释掉color去实现
> feat: add rate

- tdesign/desktop/src/divider/divider.tsx
- tdesign/desktop/src/grid/_example/base.tsx
- tdesign/desktop/src/grid/col.tsx
- tdesign/desktop/src/grid/index.html
- tdesign/desktop/src/grid/index.ts
- tdesign/desktop/src/grid/row.tsx
- tdesign/desktop/src/grid/style/index.ts
- tdesign/desktop/src/grid/type.ts
- tdesign/desktop/src/grid/vite.config.js
- tdesign/desktop/src/utils/dom.ts
初步完成grid代码，未生效样式还待研究
参考tdesign-react实现过程遇到的问题：
直接把类名赋值给<t-col>可以解决flex未生效问题，但感觉这样实现不够合理
> feat: add grid

- tdesign/desktop/site/site.config.mjs
- tdesign/desktop/site/src/meta.ts
- tdesign/desktop/src/loading/_example/base.tsx
- tdesign/desktop/src/loading/gradient.tsx
- tdesign/desktop/src/loading/index.html
- tdesign/desktop/src/loading/index.ts
- tdesign/desktop/src/loading/loading.tsx
- tdesign/desktop/src/loading/style/index.ts
- tdesign/desktop/src/loading/type.ts
- tdesign/desktop/src/loading/vite.config.js
- tdesign/desktop/src/utils/dom.ts
初步完成loading，相关功能还待测试
-----
为了实现loading的渐变图标，
我在omi的gradient组件内部使用如下代码时，\<foreignObject\>在HTML中没有并正常解析，而是被渲染为了无意义的\<foreignobject\> ，这是由于omi解析时会对节点进行特殊处理吗？
``` Typescript
render() {
return (
<svg
className={classNames(gradientClass, TdClassNamePrefix('icon-loading'))}
viewBox="0 0 14 14"
version="1.1"
width="1em"
height="1em"
xmlns="http://www.w3.org/2000/svg"
>
<foreignObject x="0" y="0" width="12" height="12">
<div class={TdClassNamePrefix(`loading__gradient-conic`)} ref={this.conicRef} />
</foreignObject>
</svg>
)
}
```
>  ![image](https://github.com/Tencent/omi/assets/48597370/cd97568e-7fdd-4c7a-8e27-eca2f5894e15)
我尝试去掉\<foreignObject\>，改为下面的代码实现了预期效果，这时svg内部的\<radialGradient\>却可以正常解析。
```Typescript
<svg
className={classNames(gradientClass, TdClassNamePrefix('icon-loading'))} …
```
> feat: add loading + svg绘制问题

- packages/omi-templates/pnpm-lock.yaml
- packages/omi-templates/src/pages/food.tsx
- packages/omi-templates/src/pages/product-docs.tsx
修复了omi-templates页面滚动自动切换右边的导航active项
> fix: omi-templates页面滚动自动切换右边的导航active项

- packages/omi/test/hooks.test.jsx
- **forwardRef钩子测试**: 覆盖初始化、ref转发、事件处理和清理机制
- **formAssociated钩子测试**: 覆盖表单关联、字段值处理、数据提取等功能
完整的功能覆盖：初始化 → 核心功能 → 清理机制
-  `packages/omi/test/hooks.test.jsx` - 新增hooks子模块单元测试
所有测试用例均通过，包括：
- forwardRef钩子: 4个测试用例
- formAssociated钩子: 5个测试用例
---
**关联Issue**: #961 补充 omi 单元测试 (任意子模块)
> feat: 补充 omi hooks 子模块单元测试 #961
