README.md
README.zh-CN.md

split Chinese and English REAMDE

---

.eslintrc
src/component.js
webpack.config.js

Can we update the version of webpack?

formate code style in src/component and webpack.config.js

---

README.md

Changed `<<!DOCTYPE html>` to `<!DOCTYPE html>`

Syntax mistake with <!DOCTYPE html>

---

README.md

changed "shadom DOM" to "shadow DOM" in README.md

corrected typos in README.md

---

README.md

Chinese version also needs to be updated which I do not know how to :)

add direct link to chrome webstore.

---

README.md

Needs to be added to .CN also.

add debugging part to readme

---

docs/main-concepts.md

Just fixing a few typos.
One is left, because there is open PR already for that.

Fix typo in main concepts

---

packages/omi/src/vdom/diff.js
packages/omi/src/we-element.js

add support for return an array of elements

增加对组件返回数组的支持

---

docs/main-concepts.md

just little typo fixed

---

README.KR.md

- Add READM of Korean
- created a REAMDE.KR.md which is written a README.md as Korean
- added a link to README.KR.md on README.md

Add README of Korean

---

docs/main-concepts.cn.md
docs/main-concepts.md

- fix wrong path to import omi
- change " as ' for the same convention

Fix documents

---

README.KR.md

update Korean README

---

README.KR.md

- update Korean README to add observe

update README Korean (Observe)

---

docs/main-concepts.kr.md
docs/main-concepts.md

add docs/main-concepts in Korean

---

tutorial/ecosystem.kr.md

- add Korean ecosystem. ecosystem.kr.md

add Korean ecosystem

---

packages/omi-cli/lib/init.js

- change wrong directory name
- as-is: **mode**_modules
- to-be: **node**_modules

fix wrong exclude directory path mode_modules as node_modules

---

README.KR.md

- Update READM KR to add (Add Omi 30 Seconds)

update READM KR (Add Omi 30 seconds)

---

README.KR.md

fixes mbox -> mobx

---

README.KR.md
docs/main-concepts.kr.md

- update README.KR.md
- update main-concepts.kr.md

update README and main-concepts KR

---

docs/main-concepts.kr.md

- Update main-concepts.kr.md
- to add static pure as true

update main-concepts kr - static pure true

---

README.KR.md
docs/main-concepts.kr.md

- update README.KR.MD
- update main-concepts.kr.md

Update Readme kr

---

README.KR.md

update REAMDE KR - useData

---

README.CN.md
README.KR.md

Fix the wrong class name in the README

fix: fix docs

---

packages/omi-element-ui/src/elements/rate/_index.css
packages/omi-element-ui/src/elements/rate/index.js
packages/omi-element-ui/src/omi-element-ui/el-rate/index.js
packages/omi-element-ui/src/omi-element-ui/style/_rate.scss
packages/omi-element-ui/src/rate.js

init feature/el-rate

---

packages/omi-cli/package.json

add omi-cli in .bin, and add version as 3.0.10

---

docs/main-concepts.cn.md

fix: docs-cn error

---

README.KR.md

update README KR - 2018.12.10

---

README.md
tutorial/the-power-of-web-components.cn.md

The Power Of Web Components 中文翻译

docs:the-power-of-web-components CN

---

packages/omio/test/browser/index.js

- remove a semi-colon in omio test

remove ; in browser/index.js

---

packages/omi-cli/lib/init-md2site.js
packages/omi-cli/lib/init-mp.js
packages/omi-cli/lib/init-mvvm.js
packages/omi-cli/lib/init-o.js
packages/omi-cli/lib/init-spa.js
packages/omi-cli/lib/init-template.js
packages/omi-cli/lib/init-ts.js
packages/omi-cli/lib/init-weui.js
packages/omi-cli/lib/init.js
packages/omi-cli/lib/install.js

Done message after created a template was not shown so I fixed the issue.
**Fixed**
- Done message will be shown
- change a omi repository url
- as-is: `https://alloyteam.github.io/omix`
- to-be: `https://github.com/Tencent/omi`
- Change a template name as correct in Done
**How to test**
``` bash
> npm i -g omi-cli-test@3.1.5
> omi-cli-test init-ts myProj
```

Omi-cli Done message

---

README.KR.md

- Update README.KR.md - **2018.12.25**

update README.KR.md - 2018.12.25

---

README.KR.md
packages/omio/README.KR.md
tutorial/omio.kr.md

Add Omio Tutorial README KR

---

README.md

Hi! Let me suggest an addition to useful resources list. I'm a maintainer of "Web Components: the Right Way" project and it has a plenty of links related to the Custom Elements, Shadow DOM etc.

Add web components the right way to useful resources

---

packages/omip/my-app/scripts/taro-cli/src/weapp.js
packages/omip/my-app/src/decorator/App.js
packages/omip/my-app/src/decorator/Page.js
packages/omip/my-app/src/pages/index/index.js

1. 让define的位置相对灵活一点
2. 加上App和Page的decorator

代码优化及新增2个decorator

---

README.md

Webpack loader for Omi.js components

eno-loader

---

README.md

A beautify extension for .omi or .eno file

omi-snippets

---

packages/omim/README.md

good luck, I'll be rooting for you

---

packages/omim/README.md

omim - update readme

---

packages/omim/README.md

omim: lock tabs

---

packages/omim/README.md

omim - README.md add tag

---

packages/omi-cli/lib/init-template.js

omi-cli: 创建小程序模版的时候更改project.config.json里的projectname字段

---

packages/omim/README.md

Write a simple one, ha ha (●＾o＾●)

omim - locking paper

---

packages/omix/utils/config.js
packages/omix/utils/create.js

When using omix, I found that the user's change to the state is not clear, so I wrote a state log print for everyone's convenience.

Added omix State log print

---

README.CN.md

添加 README.CN.md 文件里中英文间遗漏的空格，订正一些拼写错误。

update: README.CN.md

---

README.CN.md

fix the readme.cn.md format。
eg：

docs: update readme.cn.md

---

packages/omi/src/define.js
packages/omi/src/dom/index.js
packages/omi/src/extend.js

还有一个 extendStoreUpate 函数，但是很多 example 中我看都声明了一个 extendStoreUpate 函数，是否是 extendStoreUpdate ？

chore: 若干函数优化和单词拼写修复

---

packages/omi-mp/gulpfile.js

删除以前文件夹名字跟组件强匹配关系  增加组件以src 路径去生成 增加微信组件脚手架一键生成文档

删除以前文件夹名字跟组件强匹配关系  增加组件以src 路径去生成 增加微信组件脚手架一键生成文档

---

packages/omi-mp/gulpfile.js

还原样式多加载，增加默认data

---

packages/omi-mp/gulpfile.js

加了一个gulp-postcss autoprefixer 自动补全的 微信组件用到 其他用不到

加了一个gulp-postcss autoprefixer 自动补全的 微信组件用到 其他用不到

---

packages/omi-mp/scripts/mp/parse.js

编译的时候增加全局事件拦截

---

packages/omi-mp/gulpfile.js

增加helpInputEvent 事件代理 跟微信小程序事件同步

增加helpInputEvent 事件代理 跟微信小程序事件同步

---

packages/omi-mp/src/utils/helper.js

增加input 代理事件

---

packages/omi-mp/src/utils/helper.js

事件模型：找到dom属性 保持跟微信api 一样 放入detail

---

packages/omi-mp/gulpfile.js

修复window报错

---

packages/omi/src/render.js

chore: func name spelling

---

packages/omi/src/h.js
packages/omi/src/vnode.js

创建 vnode 实例修改成字面量形式，删除 vnode 文件。

chore(vnode): use object literal to create vnode

---

.gitignore
packages/omiv/package.json
packages/omiv/src/omiv.d.ts
packages/omiv/src/vue.js
packages/omiv/test/browser/components/child4.vue
packages/omiv/test/browser/components/child5.vue
packages/omiv/test/browser/components/child6.vue
packages/omiv/test/browser/components/child7.vue
packages/omiv/test/browser/components/multi-store-useSelf-$.vue
packages/omiv/test/browser/components/multi-store-useSelf.vue
packages/omiv/test/browser/index.js
packages/omiv/test/browser/vue.js
packages/omiv/test/karma.conf.js

1. 实际调用 Omiv.render 函数需要返回一个 vm 实例场景并不多，但是能够给测试提供挺大便利的。
2. 把 karma 覆盖率的注释部分打开了，添加了一条 script 。
3. 加单元测试用例， /src/vue.js 这个文件的覆盖率到 100% 了。

 Omiv.render 小优化以及添加测试用例 

---

packages/omi-mp/scripts/mp/parse.js

修复网络图片缺少字符串、修复json 转换错误

---

packages/cax/cax/svg/ellipse.js

fix: cax ellipse position

---

packages/cax/cax/svg/parse-transform.js

类似 以下存在多个 `translate` 只会作用最有后个 `translate`
`transform="translate(7.5, 9) scale(-1, 1) translate(-7.5, -9) "`

fix: transform multi prop

---

packages/omi-mp/scripts/mp/parse.js

修复代理事件bug、修复编译空格bug

---

packages/omix/utils/obaa.js

解决两个问题：
1. 目前的 obaa 处理了当 observe 的 Array 为空的时候，添加 $observeProps 的逻辑，但是没处理当 observe 的 Object 为空的时候，所以某个prop初始定义为 {} 的时候，就无法 obba.set，会报错没有定义 $observeProps
并把这个 track 逻辑封装了一下到  track 方法中
2. obaa.set 补上了已存在判断，直接 bypass 注册，直接赋值，主要不是性能，而是现在 defineProperty 普通 prop 时由于 configurable 默认 false，redefine 会报错

fix obaa.set when target object is empty && duplicate obaa.set - omix

---

packages/obaa/index.js
packages/obaa/test/test.js
packages/omix/utils/obaa.js

1. https://github.com/Tencent/omi/pull/514 改动 port 到了 obaa library，及新的 unit test
2. https://github.com/Tencent/omi/pull/514 里漏了一种 case：root 就是个空对象，fix 掉了
3. track 函数对参数验证更为严格（加了 null check）

port to obaa library && fix root plain object issue

---

packages/omix/utils/create.js

tick aggregation

---

packages/omi-mp/gulpfile.js
packages/omi-mp/package.json

Recently recommended version node 12.16.1 version does't work.
it upgrades gulp version to 4.0.2 in order to support node 12.16.1 version.

chore(omi-mp:deps): upgrade gulp version to 4.0.2.

---

README.CN.md
README.md

In the process of learning OMI, I found that the code example of CLI Template has syntax errors, so I submit the pull request

fix:README.CN JS code block syntax error

---

packages/omi-cli/bin/omi
packages/omi-cli/lib/init-vite.js
packages/omi-cli/template/vite/index.html
packages/omi-cli/template/vite/package.json
packages/omi-cli/template/vite/src/main.tsx
packages/omi-cli/template/vite/src/vite-env.d.ts
packages/omi-cli/template/vite/tsconfig.json
packages/omi-cli/template/vite/vite.config.js

feat:add cli omi-vite

---

packages/cax-omip/package.json
packages/omi-cloud/package.json
packages/omi-cloudbase/package.json
packages/omi-mp-douban/package.json
packages/omi-native/package.json
packages/omi-snake/package.json
packages/omi-snap/package.json
packages/omii/package.json
packages/omis-kbone/package.json

fix:rename package.json name

---

packages/omi/src/omi.d.ts

fix: weElement css type error

---

packages/omi/src/omi.d.ts

fix: ShadowRootPloyfill interface adoptedStyleSheets

fix: ShadowRootPloyfill interface adoptedStyleSheets

---

packages/omi/src/omi.d.ts

- add `createElement`  function type declaration
- add `cloneElement`   function type declaration

fix(types): add missing function type declaration

---

packages/admin/src/layouts/components/layout-header.tsx

fix(admin): layout-header goNotification bug-fix

fix(admin): layout-header goNotification bug-fix

---

components/card/index.html
components/card/src/demo.tsx
components/card/src/index.scss
components/card/src/index.tsx
packages/admin/src/components/components/card-component.tsx

fix(card&admin--card-component): bug fix & publish npm card 0.0.7

---

components/card/index.html
components/card/package.json
components/card/src/demo.tsx
components/card/src/index.css
components/card/src/index.scss
components/card/src/index.tsx

fix(card): attr & css optimize

fix(card): attr & css optimize

---

packages/admin/package.json
packages/admin/src/components/components/card-component.tsx

feat(admin): card-component op

feat(admin): card-component op

---

components/progress/README.md

change the defaultProps in version:0.0.3,forget to change the docs here.

docs(progress):change defaultProps

---

packages/admin/src/components/account/personal-center.tsx
packages/admin/src/components/notification/notification-list.tsx
packages/admin/src/index.tsx
packages/admin/src/l10n/en/base.ts
packages/admin/src/l10n/zh/base.ts
packages/admin/src/layouts/components/layout-header.tsx
packages/admin/src/nav-tree.ts
packages/admin/src/router.ts

feat(admin): account-center

---

packages/admin/src/components/account/personal-center.tsx

fix(admin): adjust personal-center twind

fix(admin): adjust personal-center twind

---

packages/admin/.gitignore
packages/admin/package.json
packages/admin/src/components/components/tag-component.tsx
packages/admin/src/l10n/en/base.ts
packages/admin/src/l10n/zh/base.ts
packages/admin/src/nav-tree.ts
packages/admin/src/router.ts

- add `tag` demo container for omi admin
- simplify demo component router

feat(tag): add tag demo for @omi/admin & simplify router

---

packages/admin/src/components/components/card-component.tsx

fix(admin): card-component responsive

fix(admin): card-component responsive

---

packages/admin/package.json
packages/admin/src/components/charts/bar-chart.tsx
packages/admin/src/components/charts/line-chart.tsx
packages/admin/src/l10n/en/base.ts
packages/admin/src/l10n/zh/base.ts
packages/admin/src/nav-tree.ts
packages/admin/src/router.ts

feat: add omiu-chart example 

---

packages/admin/src/layouts/components/layout-header.tsx
packages/admin/src/modules/i18n.ts

- lazyload yaml language
> https://vitejs.dev/guide/features.html#glob-import

feat: lazyload yaml as language

---

packages/admin/src/index.css
packages/admin/src/index.scss
packages/admin/src/index.tsx
packages/admin/src/layouts/basic-layout.tsx

- use scss instead of css
- add webkit scrollbar for admin
Preview:

style: add scrollbar style for admin

---

packages/omi-cli/template/component/DEV.md
packages/omi-cli/template/component/README.md
packages/omi-cli/template/component/README.zh.md
packages/omi-cli/template/component/package.json
packages/omi-cli/template/component/scripts/docs-gen.ts
packages/omi-cli/template/component/scripts/docs.ts
packages/omi-cli/template/component/scripts/locale.ts
packages/omi-cli/template/component/scripts/utils.ts
packages/omi-cli/template/component/tsconfig.json

- add docs generate script for omi-cli component template
- use typescript
- generate zh and en docs
- extract common function
- upgrade dependencies

feat: add docs gen script for omi-cli component template

---

packages/omi/src/vdom/diff.js

可以用一段代码作为可更新的最小单元；可以与标记混合使用，也可以作为可变的标记变量
`
let count = 0;
let Timer = <b>当前时间：{() => new Date().toUTCString()}</b>;
render(({ update }) => {
return (
<>
计数：{count}
<button
onClick={(evt) => {
count++;
update();
}}
>
+
</button>
{Timer}
</>
);
}, "body");
`

vnode支持function

---

tdesign/desktop/src/divider/divider.tsx
tdesign/desktop/src/divider/index.tsx
tdesign/desktop/src/link/index.tsx
tdesign/desktop/src/link/link.tsx
tdesign/desktop/src/space/_example/base.tsx
tdesign/desktop/src/space/index.html
tdesign/desktop/src/space/index.tsx
tdesign/desktop/src/space/space.tsx
tdesign/desktop/src/space/style/index.ts
tdesign/desktop/src/space/type.ts
tdesign/desktop/src/space/vite.config.js

feat: add space

---

components/card/src/index.css
tdesign/desktop/site/src/components/web/message/index.tsx
tdesign/desktop/site/src/router.ts
tdesign/desktop/site/vite.config.js
tdesign/desktop/src/index.ts
tdesign/desktop/src/message/index.html
tdesign/desktop/src/message/index.tsx
tdesign/desktop/src/message/message-us.md
tdesign/desktop/src/message/message.md
tdesign/desktop/src/message/style/index.ts
tdesign/desktop/src/message/types.ts
tdesign/desktop/src/message/vite.config.js

t-message component beta1

---

tdesign/desktop/src/textarea/index.html
tdesign/desktop/src/textarea/index.tsx
tdesign/desktop/src/textarea/style/index.ts
tdesign/desktop/src/textarea/textarea-us.md
tdesign/desktop/src/textarea/textarea.md
tdesign/desktop/src/textarea/types.ts
tdesign/desktop/src/textarea/vite.config.js

add t-textarea beta 1.0.0

---

tdesign/desktop/src/avatar/_example/adjust.tsx
tdesign/desktop/src/avatar/_example/base.tsx
tdesign/desktop/src/avatar/_example/group-cascading.tsx
tdesign/desktop/src/avatar/_example/group-max.tsx
tdesign/desktop/src/avatar/_example/group.tsx
tdesign/desktop/src/avatar/_example/shape.tsx
tdesign/desktop/src/avatar/_example/size.tsx
tdesign/desktop/src/avatar/avatar.en-US.md
tdesign/desktop/src/avatar/avatar.md
tdesign/desktop/src/avatar/avatar.tsx
tdesign/desktop/src/avatar/index.html
tdesign/desktop/src/avatar/index.tsx
tdesign/desktop/src/avatar/style/index.ts
tdesign/desktop/src/avatar/type.ts
tdesign/desktop/src/avatar/vite.config.js

这是avatar头像组件，但是功能还没完善，图像和图标部分还没做。

第一次提交，功能还没完善

---

tdesign/desktop/src/backTop/backTop-us.md
tdesign/desktop/src/backTop/backTop.md
tdesign/desktop/src/backTop/index.html
tdesign/desktop/src/backTop/index.tsx
tdesign/desktop/src/backTop/style/index.ts
tdesign/desktop/src/backTop/types.ts
tdesign/desktop/src/backTop/vite.config.js

add t-back-top beta 1.0.0

---

tdesign/desktop/site/src/components/web/comment/index.tsx
tdesign/desktop/site/src/router.ts
tdesign/desktop/src/comment/_example/base.tsx
tdesign/desktop/src/comment/_example/list.tsx
tdesign/desktop/src/comment/_example/operation.tsx
tdesign/desktop/src/comment/_example/quote.tsx
tdesign/desktop/src/comment/_example/reply-form.tsx
tdesign/desktop/src/comment/_example/reply.tsx
tdesign/desktop/src/comment/comment.en-US.md
tdesign/desktop/src/comment/comment.md
tdesign/desktop/src/comment/comment.tsx
tdesign/desktop/src/comment/index.html
tdesign/desktop/src/comment/index.tsx
tdesign/desktop/src/comment/style/index.ts
tdesign/desktop/src/comment/type.ts
tdesign/desktop/src/comment/vite.config.js
tdesign/desktop/src/divider/index.html

已经大致完成comment组件，但是里面的带回复的评论框中的关于发送回复的方法还没实现。

这是comment组件的提交

---

tdesign/desktop/site/src/components/web/comment/index.tsx
tdesign/desktop/src/comment/_example/list.tsx
tdesign/desktop/src/comment/_example/reply-form.tsx
tdesign/desktop/src/comment/_example/reply.tsx
tdesign/desktop/src/comment/comment.en-US.md
tdesign/desktop/src/comment/comment.md

修改了comment组件的相关文件，完善了部分功能，但是发送回复的功能仍然没有实现。

comment组件的完善

---

tdesign/desktop/site/src/components/web/comment/index.tsx
tdesign/desktop/site/src/components/web/link/index.tsx
tdesign/desktop/site/src/components/web/rate/index.tsx
tdesign/desktop/src/link/_example/icon.tsx
tdesign/desktop/src/link/index.html
tdesign/desktop/src/popup/_example/base.tsx
tdesign/desktop/src/popup/_example/placement.tsx
tdesign/desktop/src/popup/_example/trigger.tsx
tdesign/desktop/src/popup/index.html
tdesign/desktop/src/popup/index.ts
tdesign/desktop/src/popup/popup.tsx
tdesign/desktop/src/popup/style/index.ts
tdesign/desktop/src/popup/type.ts
tdesign/desktop/src/popup/utils.tsx
tdesign/desktop/src/popup/vite.config.js
tdesign/desktop/src/rate/_example/icon.tsx
tdesign/desktop/src/rate/index.html
tdesign/desktop/src/rate/rate.tsx
tdesign/desktop/src/utils/helper.ts

目前只完成了popup的placement和部分的trigger
另补充完善了link、rate与icon相关的内容
（目前icon不能通过l父元素控制样式）

feat: add popup and (add link icon and rate icon)

---

tdesign/desktop/src/button/index.tsx
tdesign/desktop/src/button/types.ts
tdesign/desktop/src/dropdown/_example/base.tsx
tdesign/desktop/src/dropdown/_example/multiple.tsx
tdesign/desktop/src/dropdown/dropdown.tsx
tdesign/desktop/src/dropdown/dropdownItem.tsx
tdesign/desktop/src/dropdown/dropdownMenu.tsx
tdesign/desktop/src/dropdown/index.html
tdesign/desktop/src/dropdown/index.tsx
tdesign/desktop/src/dropdown/style/index.ts
tdesign/desktop/src/dropdown/type.ts
tdesign/desktop/src/dropdown/vite.config.js
tdesign/desktop/src/link/link.tsx
tdesign/desktop/src/popup/popup.tsx
tdesign/desktop/src/utils/helper.ts
tdesign/desktop/src/utils/index.ts

feat: add dropdown

---

tdesign/desktop/src/comment/_example/reply-form.tsx
tdesign/desktop/src/comment/_example/reply.tsx
tdesign/desktop/src/textarea/index.tsx

comment组件的一点点改进

---

tdesign/desktop/site/site.config.mjs
tdesign/desktop/site/src/components/web/dropdown/index.tsx
tdesign/desktop/site/src/meta.ts
tdesign/desktop/site/src/router.ts
tdesign/desktop/src/divider/divider.tsx
tdesign/desktop/src/dropdown/_example/button.tsx
tdesign/desktop/src/dropdown/_example/child.tsx
tdesign/desktop/src/dropdown/_example/click.tsx
tdesign/desktop/src/dropdown/_example/custom.tsx
tdesign/desktop/src/dropdown/_example/disable.tsx
tdesign/desktop/src/dropdown/_example/icon.tsx
tdesign/desktop/src/dropdown/_example/left.tsx
tdesign/desktop/src/dropdown/_example/long.tsx
tdesign/desktop/src/dropdown/_example/multiple.tsx
tdesign/desktop/src/dropdown/_example/split.tsx
tdesign/desktop/src/dropdown/_example/theme.tsx
tdesign/desktop/src/dropdown/dropdown.tsx
tdesign/desktop/src/dropdown/dropdownItem.tsx
tdesign/desktop/src/dropdown/dropdownMenu.tsx
tdesign/desktop/src/dropdown/index.html
tdesign/desktop/src/popup/popup.tsx
tdesign/desktop/src/popup/style/index.ts

feat: complete dropdown and add into site

---

tdesign/desktop/site/site.config.mjs
tdesign/desktop/site/src/components/web/list/index.tsx
tdesign/desktop/site/src/router.ts
tdesign/desktop/src/list/_example/base-image-text.tsx
tdesign/desktop/src/list/_example/base-text.tsx
tdesign/desktop/src/list/_example/list-async-loading.tsx
tdesign/desktop/src/list/_example/list-header-footer.tsx
tdesign/desktop/src/list/_example/list-scroll.tsx
tdesign/desktop/src/list/_example/list-size.tsx
tdesign/desktop/src/list/_example/list-with-action.tsx
tdesign/desktop/src/list/_example/list-zebra.tsx
tdesign/desktop/src/list/_example/multiple-text.tsx
tdesign/desktop/src/list/list-item-meta.tsx
tdesign/desktop/src/list/list-item.tsx
tdesign/desktop/src/list/list.tsx
tdesign/desktop/src/list/style/index.ts

list 1.0.1 and add into site

---

tdesign/desktop/site/src/components/web/avatar/index.tsx
tdesign/desktop/src/avatar/avatar-context.tsx
tdesign/desktop/src/avatar/avatar-group.tsx
tdesign/desktop/src/avatar/avatar.tsx
tdesign/desktop/src/avatar/index.tsx

avatar组件的一些改进，但是组合头像功能仍未实现，头像图片的显示还需要Image组件的完成。

avatar组件的改进

---

tdesign/desktop/src/image/image.en-US.md
tdesign/desktop/src/image/image.tsx
tdesign/desktop/src/image/index.tsx
tdesign/desktop/src/image/style/index.ts
tdesign/desktop/src/image/type.ts

Add image components

---

tdesign/desktop/site/src/components/web/badge/index.tsx
tdesign/desktop/site/src/components/web/skeleton/index.tsx
tdesign/desktop/site/src/router.ts
tdesign/desktop/src/badge/_example/base.tsx
tdesign/desktop/src/badge/_example/color.tsx
tdesign/desktop/src/badge/_example/custom.tsx
tdesign/desktop/src/badge/_example/number.tsx
tdesign/desktop/src/badge/_example/offset.tsx
tdesign/desktop/src/badge/_example/shape.tsx
tdesign/desktop/src/badge/_example/size.tsx
tdesign/desktop/src/common/helper.ts
tdesign/desktop/src/skeleton/_example/advance.tsx
tdesign/desktop/src/skeleton/_example/animation.tsx
tdesign/desktop/src/skeleton/_example/base.tsx
tdesign/desktop/src/skeleton/_example/delay.tsx
tdesign/desktop/src/skeleton/_example/theme.tsx
tdesign/desktop/src/skeleton/index.tsx
tdesign/desktop/src/skeleton/skeleton.en-US.md
tdesign/desktop/src/skeleton/skeleton.md
tdesign/desktop/src/skeleton/skeleton.tsx
tdesign/desktop/src/skeleton/style/index.ts
tdesign/desktop/src/skeleton/type.ts

add badge and skeleton

---

packages/omi-vueify/package-lock.json
packages/omi-vueify/package.json

feat(omi-vueify): export entry

---

packages/omi-vueify/src/index.ts

feat: vueify attrs format

---

packages/omi-templates/package.json
packages/omi-templates/pnpm-lock.yaml

chore: upgrade vite to v7.0.4 and eslint to v9.31.0

---

packages/reactive-signal/package-lock.json
packages/reactive-signal/package.json
packages/reactive-signal/test/reactivity.test.jsx

test(reactive-signal): 补充单元测试 Tencent#960
